### PR TITLE
Eden3D iOS main storyboard (2018)

### PR DESCRIPTION
**Pull request by Eden3DPrinter**
This is the rough outline for our main storyboard from 2018. Please make any comments, PR's and updates please.

### CODE REVIEW

**Comment by MaxSikorski** [comment]
The outlay of the UI needs improved. I don't like how the buttons are placed, of course it needs function, etc. I will provide a rough outline of what I want to see coming in the next few days. Hopefully sooner.

**Comment by Eden3DPrinter** [comment]
I would like to merge this after the storyboard is updated some more. Max (I) will continue to work on the iOS layout.

**Comment by MaxSikorski** [comment]
The app loads fine now upon launch.

**Review by MaxSikorski — COMMENTED** [review]
This app now loads fine.

**Comment by Eden3DPrinter** [comment]
We'll share a link to the iOS test flight for the app beta download

**Pull request merged**
